homepage:
    pattern: /
    defaults: { _controller: LandmarxLandmarkBundle:Landmark:index }
landmarks:
    pattern: /
    defaults: { _controller: LandmarxLandmarkBundle:Landmark:index }
landmark_show:
    pattern: /landmarks/{slug}
    defaults: { _controller: LandmarxLandmarkBundle:Landmark:show }
    requirements:
        slug: "[\w-]+"
landmark_edit:
    pattern: /landmarks/{slug}/edit
    defaults: { _controller: LandmarxLandmarkBundle:Landmark:edit }
    requirements:
        slug: "[\w-]+"
landmark_remove:
    pattern: /landmarks/{slug}/remove
    defaults: { _controller: LandmarxLandmarkBundle:Landmark:remove }
    requirements:
        slug: "[\w-]+"  
landmark_remove_confirmed:
    pattern: /landmarks/{slug}/remove/confirmed
    defaults: { _controller: LandmarxLandmarkBundle:Landmark:removeConfirm }
    requirements:
        slug: "[\w-]+"  
landmarks_by_category:
    pattern: /categories/{slug}/landmarks
    defaults: { _controller: LandmarxLandmarkBundle:LandmarkCategory:landmarks }
    requirements:
        slug: "[\w-]+"
landmarks_by_user:
    pattern: /users/{slug}/landmarks
    defaults: { _controller: LandmarxUserBundle:User:landmarks }
    requirements:
        slug: "[\w-]+"
  
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
_security_check:
    pattern: /signin/check
_security_logout:
    pattern: /signout