services:
#    landmarx_user.menu_builder:
#        class: Landmarx\UserBundle\Menu\MenuBuilder
#        arguments: ["@knp_menu.factory"] # , @container"]
#        
#    landmarx_user.menu.main:
#        class: Knp\Menu\MenuItem
#        factory_service: landmarx_user.menu_builder
#        factory_method: createMainMenu
#        arguments: ["@request"]
#        scope: request
#        tags:
#            - { name: knp_menu.menu, alias: main }