services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    mongodb_acl_provider:
        parent: doctrine_mongodb.odm.security.acl.provider

    pagerfanta.view.default:
        class: Pagerfanta\View\DefaultView
        public: false
        tags: [{ name: pagerfanta.view, alias: default }]

    landmarx_menu.menu_builder:
        class: Landmarx\UtilityBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@security.context", "@translator"]

    landmarx_menu.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: landmarx_menu.menu_builder
        factory_method: createMainMenu
        arguments: [ "@request" ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    landmarx_menu.voter.request:
        class: Landmarx\UtilityBundle\Menu\RequestVoter
        arguments: [ "@service_container" ]
        tags:
            - { name: knp_menu.voter }