<?php

namespace Landmarx\Landmark\Twig;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-11-19 at 22:11:52.
 */
class HelperTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var Helper
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new Helper;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * @covers Landmarx\Landmark\Twig\Helper::get
   * @todo   Implement testGet().
   */
  public function testGet() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Landmarx\Landmark\Twig\Helper::render
   * @todo   Implement testRender().
   */
  public function testRender() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}
