<?php

namespace Landmarx\Landmark\Renderer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-11-19 at 22:11:52.
 */
class RendererTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var Renderer
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new Renderer;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * @covers Landmarx\Landmark\Renderer\Renderer::getCharset
   * @todo   Implement testGetCharset().
   */
  public function testGetCharset() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Landmarx\Landmark\Renderer\Renderer::setCharset
   * @todo   Implement testSetCharset().
   */
  public function testSetCharset() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}
