<?php

namespace Landmarx\Landmark\Iterator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-11-19 at 22:11:52.
 */
class DisplayedItemFilterIteratorTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var DisplayedItemFilterIterator
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new DisplayedItemFilterIterator;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * @covers Landmarx\Landmark\Iterator\DisplayedItemFilterIterator::accept
   * @todo   Implement testAccept().
   */
  public function testAccept() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Landmarx\Landmark\Iterator\DisplayedItemFilterIterator::hasChildren
   * @todo   Implement testHasChildren().
   */
  public function testHasChildren() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}
