<?php

namespace Landmarx\AttributeBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * AttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeRepository extends DocumentRepository
{
}