services:
    utility_listener:
        class: Landmarx\UtilityBundle\Listener\UtilityListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        arguments: [ @service_container ]